# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

   config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

    config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y openjdk-17-jdk maven postgresql postgresql-contrib nginx
    
  # Change VM's webserver's configuration to use shared folder.
    # (Look inside test-website.conf for specifics.)
    cp /vagrant/test-website.conf /etc/nginx/sites-available/
    # install our website configuration and disable the default
    ln -sf /etc/nginx/sites-available/test-website.conf /etc/nginx/sites-enabled/
    rm -f /etc/nginx/sites-enabled/default
    service nginx reload
  SHELL
end
