# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

   config.vm.define "webserver" do |webserver|
   webserver.vm.hostname = "webserver"
   webserver.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
   webserver.vm.network "private_network", ip: "192.168.2.11"

   webserver.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y openjdk-17-jdk maven nginx
    
  # Change VM's webserver's configuration to use shared folder.
    # (Look inside test-website.conf for specifics.)
    cp /vagrant/test-website.conf /etc/nginx/sites-available/
    # install our website configuration and disable the default
    ln -sf /etc/nginx/sites-available/test-website.conf /etc/nginx/sites-enabled/
    rm -f /etc/nginx/sites-enabled/default
    service nginx reload
    # Build and run the Spring Boot backend
    cd /vagrant/Backend
    pkill -f 'assignment-tracker-0.0.1-SNAPSHOT.jar' || true
    mvn clean package -DskipTests
    JAR_FILE=$(find /vagrant/Backend/target -maxdepth 1 -name "*.jar" ! -name "*sources*" | head -n 1)
    nohup java -jar "$JAR_FILE" \
      --spring.datasource.url="jdbc:postgresql://192.168.2.12:5432/cosc349" \
      --spring.datasource.username="postgres" \
      --spring.datasource.password="password" \
      > /var/log/backend.log 2>&1 &
    sleep 15

  SHELL
end
