spring.application.name=assignment-tracker


spring.datasource.url=jdbc:postgresql://localhost:5432/cosc349
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:changeme}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true